name: Itemizer
version: '1.0.0'

main: nl.devpieter.itemizer.Itemizer
api-version: '1.21'

authors: [ DevPieter ]
description: TODO
website: https://devpieter.nl/

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
    Utilize:
      load: BEFORE
      required: true